# Generated by Django 5.2 on 2025-04-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterdb',
            old_name='national_id',
            new_name='id_number',
        ),
    ]
