# Generated by Django 5.2 on 2025-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_rename_national_id_voterdb_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterdb',
            name='facial_encoding',
        ),
        migrations.RemoveField(
            model_name='voterdb',
            name='name',
        ),
        migrations.AddField(
            model_name='voterdb',
            name='face_image',
            field=models.ImageField(default='', upload_to='user_image/'),
            preserve_default=False,
        ),
    ]
