# Generated by Django 5.2 on 2025-05-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_voterdb_facial_encoding_remove_voterdb_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votedb',
            name='voter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vote.voterdb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voterdb',
            name='face_image',
            field=models.ImageField(upload_to='face_images/'),
        ),
    ]
