# Generated by Django 5.2 on 2025-05-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_votedb_voter_alter_voterdb_face_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
            ],
        ),
    ]
