# Generated by Django 5.2 on 2025-05-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_committeemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='name',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='hashed_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committeemember',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
