# Generated by Django 5.2 on 2025-05-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_remove_committeemember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
