# Generated by Django 5.2 on 2025-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_committeemember_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='hashed_password',
            new_name='password',
        ),
    ]
