# Generated by Django 5.2 on 2025-05-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_rename_hashed_password_committeemember_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='password',
            new_name='password_hash',
        ),
    ]
