# Generated by Django 5.2 on 2025-05-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_rename_password_committeemember_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('share', models.TextField()),
                ('signature', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='votedb',
            name='candidate',
        ),
        migrations.AddField(
            model_name='votedb',
            name='encrypted_vote',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votedb',
            name='iv',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
