# Generated by Django 5.2 on 2025-05-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_authorization_remove_votedb_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedb',
            name='voter',
        ),
        migrations.AlterField(
            model_name='votedb',
            name='iv',
            field=models.CharField(max_length=32),
        ),
    ]
