# Generated by Django 5.2 on 2025-05-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_remove_votedb_voter_alter_votedb_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='share',
        ),
    ]
