# Generated by Django 5.2 on 2025-05-28 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_remove_authorization_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='votedb',
            name='challenge',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
