# Generated by Django 5.2 on 2025-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_votedb_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedb',
            name='id',
        ),
        migrations.AlterField(
            model_name='votedb',
            name='challenge',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
