# Generated by Django 5.2 on 2025-05-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_remove_votedb_id_alter_votedb_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='share',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
